"""Add owner_id to chat rooms

Revision ID: 147ccdf0fb62
Revises: 925eae48320c
Create Date: 2026-03-17 15:43:07.761530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "147ccdf0fb62"
down_revision: Union[str, Sequence[str], None] = "925eae48320c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_rooms", sa.Column("owner_id", sa.Uuid(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_rooms", "owner_id")
    # ### end Alembic commands ###
