"""Update chat messages model

Revision ID: e7442a2bd82b
Revises: 147ccdf0fb62
Create Date: 2026-03-20 22:13:59.988748

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e7442a2bd82b"
down_revision: Union[str, Sequence[str], None] = "147ccdf0fb62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
