"""Change text is nullable True in messages model

Revision ID: e7e558940ebf
Revises: 6ece560202d4
Create Date: 2026-04-13 16:01:45.614942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7e558940ebf"
down_revision: Union[str, Sequence[str], None] = "6ece560202d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_messages",
        "text",
        existing_type=sa.VARCHAR(length=4096),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_messages",
        "text",
        existing_type=sa.VARCHAR(length=4096),
        nullable=False,
    )
    # ### end Alembic commands ###
