services:
  # --- БАЛАНСИРОВЩИК (Nginx) ---
  rt-chat-nginx:
    image: nginx:stable-alpine
    container_name: rt-chat-nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./Chat-service/template:/usr/share/nginx/html"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - rt-chat-krakend
      - rt-chat-chat-service
    restart: unless-stopped
    networks:
      - app-network

  # --- API ШЛЮЗ (Krakend) ---
  rt-chat-krakend:
    image: devopsfaith/krakend:2.4.0
    container_name: rt-chat-krakend-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    depends_on:
      - rt-chat-service
      - rt-chat-users-service
    networks:
      - app-network
  
  # --- Chat Service ---
  rt-chat-service-postgres:
    image: postgres:17
    command: -p 5432
    container_name: rt-chat-chat-postgres
    environment:
      POSTGRES_DB: ${RTCHAT_DB_NAME}
      POSTGRES_USER: ${RTCHAT_DB_USER}
      POSTGRES_PASSWORD: ${RTCHAT_DB_PWD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_rt_chat:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  rt-chat-service-redis:
    image: redis:8
    container_name: rt-chat-chat-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - redis_data_chat:/data
    command: redis-server --appendonly yes --appendfsync everysec
    networks:
      - app-network

  rt-chat-service:
    build:
      context: ./Chat-service
      dockerfile: Dockerfile
    container_name: rt-chat-chat-service
    ports:
      - "8001:8001"
    environment:
      RTCHAT_APP_MODE: PROD
      RTCHAT_DB_HOST: rt-chat-service-postgres
      RTCHAT_DB_PORT: 5432
      RTCHAT_DB_NAME: ${RTCHAT_DB_NAME}
      RTCHAT_DB_USER: ${RTCHAT_DB_USER}
      RTCHAT_DB_PWD: ${RTCHAT_DB_PWD}
      RTCHAT_REDIS_HOST: rt-chat-service-redis
      RTCHAT_REDIS_PORT: 6379
    depends_on:
      rt-chat-service-postgres:
        condition: service_healthy
      rt-chat-service-redis:
        condition: service_healthy
    command: ["bash", "-c", "alembic upgrade head && python -m application.web"]
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - app-network

  # --- Users Service ---
  rt-chat-users-service-postgres:
    image: postgres:17
    command: -p 5433
    container_name: rt-chat-users-postgres
    environment:
      POSTGRES_DB: ${USERS_DB_NAME}
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PWD}
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5433 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  rt-chat-users-service-redis:
    image: redis:7-alpine
    container_name: rt-chat-users-redis
    ports:
      - "6380:6380"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - redis_data_users:/data
    command: redis-server --port 6380 --appendonly yes --appendfsync everysec
    networks:
      - app-network

  rt-chat-users-service:
    build:
      context: ./Users-service
      dockerfile: dockerfile
    container_name: rt-chat-users-service
    ports:
      - "8002:8002"
    environment:
      USERS_APP_MODE: PROD
      USERS_DB_HOST: rt-chat-users-service-postgres
      USERS_DB_PORT: 5433
      USERS_DB_NAME: ${USERS_DB_NAME}
      USERS_DB_USER: ${USERS_DB_USER}
      USERS_DB_PWD: ${USERS_DB_PWD}
      USERS_REDIS_HOST: rt-chat-users-service-redis
      USERS_REDIS_PORT: 6380
    depends_on:
      rt-chat-users-service-postgres:
        condition: service_healthy
      rt-chat-users-service-redis:
        condition: service_healthy
    command: ["bash", "-c", "alembic upgrade head && python main.py"]
    restart: always
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - app-network

volumes:
  postgres_data_rt_chat:
  redis_data_chat:
  postgres_data_users:
  redis_data_users:

networks:
  app-network:
    driver: bridge
