services:
  # Extended config
  # Service name                    Service role
  # rt_chat-nginx-balancer	        Nginx
  # rt_chat-krakend-gateway	        KrakenD
  # rt_chat-chat-api	              Chat FastAPI
  # rt_chat-chat-postgres	          БД чата
  # rt_chat-users-api	              Users FastAPI
  # rt_chat-users-postgres	        БД пользователей
  # rt_chat-users-redis	            Redis пользователей
  # rt_chat-media-api	              Media FastAPI
  # rt_chat-media-postgres	        БД медиа
  # rt_chat-media-rabbitmq	        RabbitMQ (Ext)
  # rt_chat-media-outbox_producer	  Outbox воркер (Ext)
  # rt_chat-media-file_processor	  File processor (Ext)
  # rt_chat-media-clamav            Clamav сканер вирусов
  
  # --- БАЛАНСИРОВЩИК (Nginx) ---
  rt_chat-nginx:
    image: nginx:stable-alpine
    container_name: rt_chat-nginx
    ports:
      - "80:80"
    volumes:
      - './nginx.conf.template:/etc/nginx/nginx.conf.template'
      - "./Chat-service/template:/usr/share/nginx/html"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - rt_chat-krakend-gateway
      - rt_chat-chat-api
      - rt_chat-users-api
      - rt_chat-frontend
    environment:
      - SERVER_NAME=${SERVER_NAME}
    command: ["/bin/sh", "-c", "envsubst '${SERVER_NAME}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
    restart: unless-stopped
    networks:
      - app-network

  # --- API ШЛЮЗ (Krakend) ---
  rt_chat-krakend-gateway:
    image: devopsfaith/krakend:2.4.0
    container_name: rt_chat-krakend-gateway
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    depends_on:
      rt_chat-chat-api:
        condition: service_started
      rt_chat-users-api:
        condition: service_started
    networks:
      - app-network

  # --- Frontend ---
  rt_chat-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_GW_URL=http://${SERVER_NAME}/api-gateway
        - VITE_WS_URL=ws://${SERVER_NAME}
    container_name: rt_chat-frontend
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - app-network

  # --- Chat Service ---
  rt_chat-chat-postgres:
    image: postgres:17
    command: -p 5432
    container_name: rt_chat-chat-postgres
    environment:
      POSTGRES_DB: ${RTCHAT_DB_NAME}
      POSTGRES_USER: ${RTCHAT_DB_USER}
      POSTGRES_PASSWORD: ${RTCHAT_DB_PWD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_rt_chat:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  rt_chat-chat-api:
    build:
      context: ./Chat-service
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    container_name: rt_chat-chat-api
    environment:
      RTCHAT_APP_MODE: ${RTCHAT_APP_MODE}
      RTCHAT_DB_HOST: rt_chat-chat-postgres
      RTCHAT_DB_PORT: 5432
      RTCHAT_DB_NAME: ${RTCHAT_DB_NAME}
      RTCHAT_DB_USER: ${RTCHAT_DB_USER}
      RTCHAT_DB_PWD: ${RTCHAT_DB_PWD}
    depends_on:
      rt_chat-chat-postgres:
        condition: service_healthy
    command: ["bash", "-c", "alembic upgrade head && python -m application.web"]
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - app-network

  # --- Users Service ---
  rt_chat-users-postgres:
    image: postgres:17
    command: -p 5433
    container_name: rt_chat-users-postgres
    environment:
      POSTGRES_DB: ${USERS_DB_NAME}
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PWD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5433 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  rt_chat-users-redis:
    image: redis:7-alpine
    container_name: rt_chat-users-redis
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - redis_data_users:/data
    command: redis-server --port 6380 --appendonly yes --appendfsync everysec
    networks:
      - app-network

  rt_chat-users-api:
    build:
      context: ./Users-service
      dockerfile: dockerfile
    ports:
      - 8002:8002
    container_name: rt_chat-users-api
    environment:
      USERS_APP_MODE: ${USERS_APP_MODE}
      USERS_DB_HOST: rt_chat-users-postgres
      USERS_DB_PORT: 5433
      USERS_DB_NAME: ${USERS_DB_NAME}
      USERS_DB_USER: ${USERS_DB_USER}
      USERS_DB_PWD: ${USERS_DB_PWD}
      USERS_REDIS_HOST: rt_chat-users-redis
      USERS_REDIS_PORT: 6380
    depends_on:
      rt_chat-users-postgres:
        condition: service_healthy
      rt_chat-users-redis:
        condition: service_healthy
    command: ["bash", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8002"]
    restart: always
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - app-network

  # --- Media Service ---
  rt_chat-media-postgres:
    image: postgres:17
    command: -p 5434
    container_name: rt_chat-media-postgres
    environment:
      POSTGRES_DB: ${MEDIA__DB__NAME}
      POSTGRES_USER: ${MEDIA__DB__USER}
      POSTGRES_PASSWORD: ${MEDIA__DB__PWD}
    ports:
      - "5434:5434"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5434 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_media:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  rt_chat-media-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rt_chat-media-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${MEDIA__RABBITMQ__LOGIN}
      RABBITMQ_DEFAULT_PASS: ${MEDIA__RABBITMQ__PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  rt_chat-media-clamav:
    image: clamav/clamav:stable
    container_name: rt_chat-media-clamav
    volumes:
    - ./Media-service/application/clamav_data:/var/lib/clamav  # ← базы сигнатур
    networks:
      - app-network

  rt_chat-media-outbox_producer:
    build:
      context: ./Media-service
      dockerfile: Dockerfile
    container_name: rt_chat-media-outbox_producer
    env_file:
      - ./.env
    environment:
      MEDIA__APP__MODE: ${MEDIA__APP__MODE}

      MEDIA__DB__HOST: rt_chat-media-postgres
      MEDIA__DB__PORT: 5434
      MEDIA__DB__NAME: ${MEDIA__DB__NAME}
      MEDIA__DB__USER: ${MEDIA__DB__USER}
      MEDIA__DB__PWD: ${MEDIA__DB__PWD}

      MEDIA__S3__ACCESSKEY: ${MEDIA__S3__ACCESSKEY}
      MEDIA__S3__SECRETKEY: ${MEDIA__S3__SECRETKEY}
      MEDIA__S3__ENDPOINTURL: ${MEDIA__S3__ENDPOINTURL}
      MEDIA__S3__BUCKETNAME: ${MEDIA__S3__BUCKETNAME}

      MEDIA__RABBITMQ__HOST: rt_chat-media-rabbitmq
      MEDIA__RABBITMQ__PORT: 5672
      MEDIA__RABBITMQ__LOGIN: ${MEDIA__RABBITMQ__LOGIN}
      MEDIA__RABBITMQ__PASSWORD: ${MEDIA__RABBITMQ__PASSWORD}

      MEDIA__OUTBOX__POLL_INTERVAL: ${MEDIA__OUTBOX__POLL_INTERVAL}
    depends_on:
      rt_chat-media-postgres:
        condition: service_healthy
      rt_chat-media-rabbitmq:
        condition: service_healthy
    command: python -m application.outbox_producer_worker
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - app-network

  rt_chat-media-outbox_consumer:
    build:
      context: ./Media-service
      dockerfile: Dockerfile
    container_name: rt_chat-media-outbox_consumer
    env_file:
      - ./.env
    environment:
      MEDIA__APP__MODE: ${MEDIA__APP__MODE}

      MEDIA__DB__HOST: rt_chat-media-postgres
      MEDIA__DB__PORT: 5434
      MEDIA__DB__NAME: ${MEDIA__DB__NAME}
      MEDIA__DB__USER: ${MEDIA__DB__USER}
      MEDIA__DB__PWD: ${MEDIA__DB__PWD}

      MEDIA__S3__ACCESSKEY: ${MEDIA__S3__ACCESSKEY}
      MEDIA__S3__SECRETKEY: ${MEDIA__S3__SECRETKEY}
      MEDIA__S3__ENDPOINTURL: ${MEDIA__S3__ENDPOINTURL}
      MEDIA__S3__BUCKETNAME: ${MEDIA__S3__BUCKETNAME}

      MEDIA__RABBITMQ__HOST: rt_chat-media-rabbitmq
      MEDIA__RABBITMQ__PORT: 5672
      MEDIA__RABBITMQ__LOGIN: ${MEDIA__RABBITMQ__LOGIN}
      MEDIA__RABBITMQ__PASSWORD: ${MEDIA__RABBITMQ__PASSWORD}

      MEDIA__OUTBOX__POLL_INTERVAL: ${MEDIA__OUTBOX__POLL_INTERVAL}
    depends_on:
      rt_chat-media-postgres:
        condition: service_healthy
      rt_chat-media-rabbitmq:
        condition: service_healthy
    command: python -m application.outbox_consumer_worker
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - app-network

  rt_chat-media-api:
    build:
      context: ./Media-service
      dockerfile: Dockerfile
    container_name: rt_chat-media-api
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    environment:
      MEDIA__APP__MODE: ${MEDIA__APP__MODE}

      MEDIA__DB__HOST: rt_chat-media-postgres
      MEDIA__DB__PORT: 5434
      MEDIA__DB__NAME: ${MEDIA__DB__NAME}
      MEDIA__DB__USER: ${MEDIA__DB__USER}
      MEDIA__DB__PWD: ${MEDIA__DB__PWD}

      MEDIA__S3__ACCESSKEY: ${MEDIA__S3__ACCESSKEY}
      MEDIA__S3__SECRETKEY: ${MEDIA__S3__SECRETKEY}
      MEDIA__S3__ENDPOINTURL: ${MEDIA__S3__ENDPOINTURL}
      MEDIA__S3__BUCKETNAME: ${MEDIA__S3__BUCKETNAME}

      MEDIA__RABBITMQ__HOST: rt_chat-media-rabbitmq
      MEDIA__RABBITMQ__PORT: 5672
      MEDIA__RABBITMQ__LOGIN: ${MEDIA__RABBITMQ__LOGIN}
      MEDIA__RABBITMQ__PASSWORD: ${MEDIA__RABBITMQ__PASSWORD}

      MEDIA__OUTBOX__POLL_INTERVAL: ${MEDIA__OUTBOX__POLL_INTERVAL}
    depends_on:
      rt_chat-media-postgres:
        condition: service_healthy
      rt_chat-media-rabbitmq:
        condition: service_healthy
      rt_chat-media-clamav:
        condition: service_started
      rt_chat-media-outbox_producer:
        condition: service_started
      rt_chat-media-outbox_consumer:
        condition: service_started
    command: ["bash", "-c", "alembic upgrade head && python -m application.web"]
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    networks:
      - app-network

  # --- Monitoring / Logs (Prometheus + Loki + Grafana) ---
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: rt_chat-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped
    networks:
      - app-network

  loki:
    image: grafana/loki:3.5.1
    container_name: rt_chat-loki
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - loki_data:/loki
    command: ["-config.file=/etc/loki/config.yml"]
    restart: unless-stopped
    networks:
      - app-network

  promtail:
    image: grafana/promtail:3.5.1
    container_name: rt_chat-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["-config.file=/etc/promtail/config.yml"]
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:12.2.0
    container_name: rt_chat-grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - prometheus
      - loki

volumes:
  postgres_data_rt_chat:
  redis_data_chat:
  postgres_data_users:
  redis_data_users:
  postgres_data_media:
  rabbitmq_data:
    driver: local
  prometheus_data:
  loki_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
