user root;
worker_processes 1;

events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name 176.12.67.28;
        charset utf-8;

        # Фронтенд
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # KrakenD API Gateway
        location /api-gateway/ {
            client_max_body_size 200M;

            rewrite ^/api-gateway/(.*)$ /$1 break;
            proxy_pass http://rt-chat-krakend:8080/;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # WebSocket — напрямую на chat-service
        location /ws/ {
            proxy_pass http://rt-chat-chat-service:8001;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
        }
    }
}
