FROM python:3.14-slim

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction

COPY . /app/

RUN mkdir -p /app/core/security_keys \
    && python -c "\
from cryptography.hazmat.primitives.asymmetric import ed25519; \
from cryptography.hazmat.primitives import serialization; \
pk = ed25519.Ed25519PrivateKey.generate(); \
open('/app/core/security_keys/private_key.pem','wb').write(pk.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption())); \
open('/app/core/security_keys/public_key.pem','wb').write(pk.public_key().public_bytes(serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo))"

EXPOSE 8002
