"""Add user roles, created_at and updated_at mixins

Revision ID: 23c028c0ede1
Revises: 492ee9b9f00f
Create Date: 2026-02-21 15:19:02.501318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23c028c0ede1"
down_revision: Union[str, Sequence[str], None] = "492ee9b9f00f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку как nullable
    op.add_column("users", sa.Column("role", sa.String(), nullable=True))
    
    # Заполняем существующие строки
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    
    # Делаем колонку NOT NULL
    op.alter_column("users", "role", nullable=False)

    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
