"""Cahnge avatar type: uuid to str

Revision ID: a0da45965aaf
Revises: 0d8b0cdeecc8
Create Date: 2026-04-14 17:28:04.028333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0da45965aaf"
down_revision: Union[str, Sequence[str], None] = "0d8b0cdeecc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "avatar",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "avatar",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
