"""Remove email in users model

Revision ID: 987f0f1dcc27
Revises: 86d3aef82d5e
Create Date: 2026-03-27 12:59:59.739046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "987f0f1dcc27"
down_revision: Union[str, Sequence[str], None] = "86d3aef82d5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
