"""Add is_linked in file metadata model

Revision ID: a58215796a39
Revises: d3ade92aa386
Create Date: 2026-04-05 01:45:01.147342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a58215796a39"
down_revision: Union[str, Sequence[str], None] = "d3ade92aa386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files_metadata_orms",
        sa.Column("is_linked", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "files_metadata_orms",
        sa.Column("linked_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files_metadata_orms", "linked_at")
    op.drop_column("files_metadata_orms", "is_linked")
    # ### end Alembic commands ###
