"""Create file outbox

Revision ID: d3ade92aa386
Revises: f4abbb13456a
Create Date: 2026-03-13 23:55:21.531567

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3ade92aa386"
down_revision: Union[str, Sequence[str], None] = "f4abbb13456a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_outbox_orms",
        sa.Column("message_name", sa.String(), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("traceparent", sa.String(), nullable=True),
        sa.Column(
            "created_at_db",
            sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at_db",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files_outbox_orms")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files_outbox_orms")
    # ### end Alembic commands ###
