"""Create file metadata model

Revision ID: f4abbb13456a
Revises:
Create Date: 2026-03-13 23:53:42.223814

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4abbb13456a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_metadata_orms",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("upload_context", sa.String(length=100), nullable=False),
        sa.Column("s3_url", sa.String(length=512), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at_db",
            sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at_db",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files_metadata_orms")),
        sa.UniqueConstraint("s3_url", name=op.f("uq_files_metadata_orms_s3_url")),
    )
    op.create_index(
        op.f("ix_files_metadata_orms_file_id"),
        "files_metadata_orms",
        ["file_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_files_metadata_orms_file_id"),
        table_name="files_metadata_orms",
    )
    op.drop_table("files_metadata_orms")
    # ### end Alembic commands ###
